# Default values for helm-chart.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

frontend:
  name: frontend
  image:
    repository: andrejtaneski/conduit_frontend
    pullPolicy: Always
    tag: main
    port: 4200
  service:
    name: frontend
    type: NodePort
    port: 4200

backend:
  name: backend
  image:
    repository: andrejtaneski/conduit_backend
    pullPolicy: Always
    tag: main
    port: 8080
  service:
    name: backend
    type: NodePort
    port: 8080

db:
  name: postgres
  image:
    repository: postgres
    pullPolicy: Always
    port: 5432
  service:
    name: backend
    type: NodePort
    port: 5432

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80
