apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  labels:
    app: conduit_backend
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "helm-chart.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "helm-chart.selectorLabels" . | nindent 8 }}
    spec:
      containers:
      - name: backend
        image: andrejtaneski/conduit_backend:main
        env:
          - name: USER_NAME
            value: user
          - name: PASSWORD
            value: password
          - name: DB_HOST
            value: postgres
          - name: DB
            value: test-db
          - name: PORT
            value: "8080"
        imagePullPolicy: Always
        ports:
        - name: http-backend
          containerPort: 8080
          protocol: TCP