apiVersion: v1
kind: Service
metadata:
  name: postgres
  labels:
    {{- include "helm-chart.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: 5432
      targetPort: db-port
      protocol: TCP
      name: db-port
  selector:
    {{- include "helm-chart.selectorLabels" . | nindent 4 }}
