apiVersion: v1
kind: Service
metadata:
  name: backend
  labels:
    {{- include "helm-chart.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: 8080
      targetPort: http-backend
      protocol: TCP
      name: http-backend
  selector:
    {{- include "helm-chart.selectorLabels" . | nindent 4 }}
